services:
  kafka:
    image: bitnami/kafka:3.8.0
    environment:

      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_LOG_DIRS=/bitnami/kafka/data
      # - KAFKA_ALLOW_PLAINTEXT_LISTENER=yes
      # - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_MAX_MESSAGE_SIZE=2097152000  # 2000 MB
      - KAFKA_MESSAGE_MAX_BYTES=2097152000  # 2000 MB
    ports:
      - '9094:9094'
    volumes:
      - kafka_data:/bitnami/kafka/data

  minio:
    image: minio/minio:RELEASE.2024-10-13T13-34-11Z
    environment:
      - MINIO_ROOT_USER=miniouser
      - MINIO_ROOT_PASSWORD=minio577715
    ports:
      - '9110:9000'
      - '9011:9001'
    command: server /data --console-address ":9001"  # 明确指定控制台端口
    volumes:
      - minio_data:/data

  mongodb:
    image: mongo:7.0.12
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser  # 替换为你的用户名
      MONGO_INITDB_ROOT_PASSWORD: mongo577715  # 替换为你的密码
    volumes:
      - mongo_data:/data/db  # 数据持久化

  redis:
    image: redis:7.2.5
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "redis577715"]

  mysql:
    image: mysql:8.0.35
    environment:
      - MYSQL_ROOT_PASSWORD=mysql?577715
      - MYSQL_DATABASE=imagedb
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysql577715
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
  

volumes:
  kafka_data:
    driver: local
  minio_data:
    driver: local
  redis_data:
    driver: local
  mysql_data:
    driver: local
  mongo_data:
    driver: local
